name: Scheduled GET Request

on:
  schedule:
    - cron: "0 0 * * 0" # Runs every sunday at midnight
  workflow_dispatch: # Allows manual trigger from GitHub Actions UI

jobs:
  get-request:
    runs-on: ubuntu-latest

    steps:
      - name: Send GET Request
        run: |
          curl -v --fail "${{ secrets.TARGET_URL }}"
